---
title: "Экспорт Республики Адыгеи"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(ggfittext)
library(treemapify)
library(lubridate)
theme_set(theme_bw())
options(scipen=999)

read_csv("adyghe.csv") %>% 
  filter(NAPR == "ЭК") %>% 
  mutate(PERIOD = paste0("01/", PERIOD), 
         PERIOD = lubridate::dmy(PERIOD),
         PERIOD_m = month(PERIOD),
         PERIOD_y = year(PERIOD)) %>% 
  left_join(read_csv("country.csv", skip = 1), by = c("STRANA" = "KOD")) %>% 
  left_join(read_csv("tnved.csv", skip = 1), by = c("TNVED" = "KOD")) ->
  df
```


# Общий {.tabset .tabset-fade .tabset-pills}

## 2013
```{r}
selected_year <- 2013
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>% 
  mutate(type = if_else(type == "NETTO", "Нетто", "Стоимость"),
         label = paste0(NAME, ": ", value)) %>% 
  ggplot(aes(x = PERIOD, y = value, z = label))+
  geom_point()+
  facet_grid(PERIOD_y~type, scales = "free")+
  scale_y_log10()+
  labs(x = "", y = "стоимоть закупки (лог. шкала)")->
  plot

plotly::ggplotly(plot, tooltip = "z")
```

## 2014
```{r}
selected_year <- 2014
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>% 
  ggplot(aes(x = PERIOD, value))+
  geom_point()+
  facet_grid(PERIOD_y~type, scales = "free")+
  scale_y_log10()+
  labs(x = "", y = "деньги (лог. шкала)")
```

## 2015
```{r}
selected_year <- 2015
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>% 
  ggplot(aes(x = PERIOD, value))+
  geom_point()+
  facet_grid(PERIOD_y~type, scales = "free")+
  scale_y_log10()+
  labs(x = "", y = "деньги (лог. шкала)")
```

## 2016
```{r}
selected_year <- 2016
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>% 
  ggplot(aes(x = PERIOD, value))+
  geom_point()+
  facet_grid(PERIOD_y~type, scales = "free")+
  scale_y_log10()+
  labs(x = "", y = "деньги (лог. шкала)")
```

## 2017
```{r}
selected_year <- 2017
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>% 
  ggplot(aes(x = PERIOD, value))+
  geom_point()+
  facet_grid(PERIOD_y~type, scales = "free")+
  scale_y_log10()+
  labs(x = "", y = "деньги (лог. шкала)")
```

# По странам {.tabset .tabset-fade .tabset-pills}

## 2013
```{r, fig.height=16}
selected_year <- 2013
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(PERIOD, NAME, type) %>% 
  mutate(value = sum(value)) %>% 
  ggplot(aes(x = PERIOD, y = value, color = NAME))+
  geom_point(show.legend = FALSE)+
  facet_grid(NAME~type, margins = "NAME")+
  scale_y_log10()+
  labs(x = "", y = "сумма денег (лог. шкала)")
```

## 2014
```{r, fig.height=16}
selected_year <- 2014
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(PERIOD, NAME, type) %>% 
  mutate(value = sum(value)) %>% 
  ggplot(aes(x = PERIOD, y = value, color = NAME))+
  geom_point(show.legend = FALSE)+
  facet_grid(NAME~type, margins = "NAME")+
  scale_y_log10()+
  labs(x = "", y = "сумма денег (лог. шкала)")
```

## 2015
```{r, fig.height=16}
selected_year <- 2015
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(PERIOD, NAME, type) %>% 
  mutate(value = sum(value)) %>% 
  ggplot(aes(x = PERIOD, y = value, color = NAME))+
  geom_point(show.legend = FALSE)+
  facet_grid(NAME~type, margins = "NAME")+
  scale_y_log10()+
  labs(x = "", y = "сумма денег (лог. шкала)")
```

## 2016
```{r, fig.height=16}
selected_year <- 2016
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(PERIOD, NAME, type) %>% 
  mutate(value = sum(value)) %>% 
  ggplot(aes(x = PERIOD, y = value, color = NAME))+
  geom_point(show.legend = FALSE)+
  facet_grid(NAME~type, margins = "NAME")+
  scale_y_log10()+
  labs(x = "", y = "сумма денег (лог. шкала)")
```

## 2017
```{r, fig.height=16}
selected_year <- 2017
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(PERIOD, NAME, type) %>% 
  mutate(value = sum(value)) %>% 
  ggplot(aes(x = PERIOD, y = value, color = NAME))+
  geom_point(show.legend = FALSE)+
  facet_grid(NAME~type, margins = "NAME")+
  scale_y_log10()+
  labs(x = "", y = "сумма денег (лог. шкала)")
```

# По видам продукции {.tabset .tabset-fade .tabset-pills}
## 2013
```{r}
selected_year <- 2013
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(TNVED, SIMPLE_NAM, type) %>% 
  summarise(value = sum(value)) %>% 
  ggplot(aes(area = value, label = SIMPLE_NAM, fill = TNVED))+
  geom_treemap(show.legend = FALSE)+
  geom_treemap_text(
    fontface = "italic",
    colour = "white",
    place = "centre",
    grow = TRUE) +
  facet_wrap(~type)
```

## 2014
```{r}
selected_year <- 2014
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(TNVED, SIMPLE_NAM, type) %>% 
  summarise(value = sum(value)) %>% 
  ggplot(aes(area = value, label = SIMPLE_NAM, fill = TNVED))+
  geom_treemap(show.legend = FALSE)+
  geom_treemap_text(
    fontface = "italic",
    colour = "white",
    place = "centre",
    grow = TRUE) +
  facet_wrap(~type)
```

## 2015
```{r}
selected_year <- 2015
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(TNVED, SIMPLE_NAM, type) %>% 
  summarise(value = sum(value)) %>% 
  ggplot(aes(area = value, label = SIMPLE_NAM, fill = TNVED))+
  geom_treemap(show.legend = FALSE)+
  geom_treemap_text(
    fontface = "italic",
    colour = "white",
    place = "centre",
    grow = TRUE) +
  facet_wrap(~type)
```

## 2016
```{r}
selected_year <- 2016
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(TNVED, SIMPLE_NAM, type) %>% 
  summarise(value = sum(value)) %>% 
  ggplot(aes(area = value, label = SIMPLE_NAM, fill = TNVED))+
  geom_treemap(show.legend = FALSE)+
  geom_treemap_text(
    fontface = "italic",
    colour = "white",
    place = "centre",
    grow = TRUE) +
  facet_wrap(~type)
```

## 2017
```{r}
selected_year <- 2017
df  %>%
  filter(PERIOD_y == selected_year) %>% 
  gather(type, value, STOIM:NETTO) %>%
  group_by(TNVED, SIMPLE_NAM, type) %>% 
  summarise(value = sum(value)) %>% 
  ggplot(aes(area = value, label = SIMPLE_NAM, fill = TNVED))+
  geom_treemap(show.legend = FALSE)+
  geom_treemap_text(
    fontface = "italic",
    colour = "white",
    place = "centre",
    grow = TRUE) +
  facet_wrap(~type)
```
